### ISSUE TITLE
Éviter les doubles réponses?

### ISSUE THREAD

**Issue by chmduquesne** [martinkirch/tofbot#24]
Pour l'instant, vu que tous les plugins reçoivent tous les messages, on peut avoir plusieurs réaction du bot pour un seul message. On pourrait empêcher ce comportement en arrêtant la propagation aux plugins si l'un deux invoque la méthode msg.

**Comment by martinkirch** [comment]
Ouaip, par contre les URLs ne passent pas par le filtre pour ne pas ouvrir la porte aux rick'rolling.
